version: '3.8'

services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - "8008:11434"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      host_ip: ${host_ip}
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
